export const townSeed = {
  id: "rookwood",
  name: "Rookwood",
  weather: "Cold and clear",
  locations: [
    { id: "bakery", name: "Sunrise Bakery", type: "Workplace", x: 24, y: 62 },
    { id: "square", name: "Founders Square", type: "Civic", x: 52, y: 42 },
    { id: "workshop", name: "North Workshop", type: "Workplace", x: 76, y: 25 },
    { id: "cottages", name: "South Cottages", type: "Residential", x: 66, y: 76 },
  ],
  residents: [
    {
      id: "mara",
      name: "Mara Venn",
      role: "Baker",
      homeLocationId: "cottages",
      workLocationId: "bakery",
      initialLocationId: "cottages",
      energy: 72,
      hunger: 34,
      mood: "Sleepy",
    },
    {
      id: "otis",
      name: "Otis Bell",
      role: "Mechanic",
      homeLocationId: "cottages",
      workLocationId: "workshop",
      initialLocationId: "cottages",
      energy: 64,
      hunger: 28,
      mood: "Tired",
    },
    {
      id: "sal",
      name: "Sal Orin",
      role: "Courier",
      homeLocationId: "cottages",
      workLocationId: "square",
      initialLocationId: "cottages",
      energy: 84,
      hunger: 22,
      mood: "Restless",
    },
  ],
};
