const sharedLocations = [
  { id: "bakery", name: "Sunrise Bakery", type: "Workplace", x: 24, y: 58 },
  { id: "square", name: "Founders Square", type: "Civic", x: 50, y: 43 },
  { id: "workshop", name: "North Workshop", type: "Workplace", x: 77, y: 27 },
  { id: "south-cottages", name: "South Cottages", type: "Residential", x: 67, y: 80 },
  { id: "east-cottages", name: "East Cottages", type: "Residential", x: 88, y: 65 },
  { id: "hill-houses", name: "Hill Houses", type: "Residential", x: 68, y: 11 },
  { id: "general-store", name: "General Store", type: "Commerce", x: 28, y: 31 },
  { id: "schoolhouse", name: "Old Schoolhouse", type: "Civic", x: 56, y: 17 },
  { id: "clinic", name: "The Small Clinic", type: "Civic", x: 87, y: 43 },
  { id: "inn", name: "The Lantern Inn", type: "Commerce", x: 45, y: 72 },
  { id: "farm", name: "Westfield Farm", type: "Workplace", x: 13, y: 82 },
];

const relationships = [
  { id: "rel-mara-otis", fromId: "mara", toId: "otis", kind: "friends", strength: 62 },
  { id: "rel-mara-irena", fromId: "mara", toId: "irena", kind: "old friends", strength: 64 },
  { id: "rel-mara-pella", fromId: "mara", toId: "pella", kind: "neighbors", strength: 55 },
  { id: "rel-otis-bram", fromId: "otis", toId: "bram", kind: "workmates", strength: 72 },
  { id: "rel-otis-nell", fromId: "otis", toId: "nell", kind: "old debt", strength: 38 },
  { id: "rel-sal-june", fromId: "sal", toId: "june", kind: "courier contact", strength: 48 },
  { id: "rel-sal-corin", fromId: "sal", toId: "corin", kind: "friendly", strength: 57 },
  { id: "rel-june-nell", fromId: "june", toId: "nell", kind: "colleagues", strength: 66 },
  { id: "rel-corin-irena", fromId: "corin", toId: "irena", kind: "business rivals", strength: 35 },
  { id: "rel-thom-pella", fromId: "thom", toId: "pella", kind: "farm partners", strength: 74 },
  { id: "rel-bram-corin", fromId: "bram", toId: "corin", kind: "customer", strength: 42 },
  { id: "rel-irena-nell", fromId: "irena", toId: "nell", kind: "neighbors", strength: 51 },
];

function resident({
  id,
  name,
  role,
  homeLocationId,
  workLocationId,
  energy,
  hunger,
  mood,
  action = "work",
  workStart,
  workEnd,
  workReason,
  workStatus,
  workMood = "Focused",
  mealStart,
  mealEnd,
  mealLocationId = workLocationId,
  mealReason,
  mealStatus,
  mealMood = "Content",
  eveningAction,
  eveningStart,
  eveningEnd,
  eveningLocationId,
  eveningReason,
  eveningStatus,
  eveningMood,
}) {
  return {
    id,
    name,
    role,
    homeLocationId,
    workLocationId,
    initialLocationId: homeLocationId,
    energy,
    hunger,
    mood,
    routine: {
      action,
      workStart,
      workEnd,
      workReason,
      workStatus,
      workMood,
      mealStart,
      mealEnd,
      mealLocationId,
      mealReason,
      mealStatus,
      mealMood,
      eveningAction,
      eveningStart,
      eveningEnd,
      eveningLocationId,
      eveningReason,
      eveningStatus,
      eveningMood,
    },
  };
}

export const townSeed = {
  id: "rookwood",
  name: "Rookwood",
  weather: "Cold and clear",
  locations: sharedLocations,
  residents: [
    resident({
      id: "mara",
      name: "Mara Venn",
      role: "Baker",
      homeLocationId: "south-cottages",
      workLocationId: "bakery",
      energy: 72,
      hunger: 34,
      mood: "Sleepy",
      workStart: 5,
      workEnd: 12,
      workReason: "the bakery needs someone on duty",
      workStatus: "Opening the ovens",
      mealStart: 12,
      mealEnd: 14,
      mealReason: "the morning shift is over",
      mealStatus: "Eating behind the bakery",
    }),
    resident({
      id: "otis",
      name: "Otis Bell",
      role: "Mechanic",
      homeLocationId: "south-cottages",
      workLocationId: "workshop",
      energy: 64,
      hunger: 28,
      mood: "Tired",
      workStart: 8,
      workEnd: 18,
      workReason: "a repair is waiting at the workshop",
      workStatus: "Sorting a stubborn gearbox",
      workMood: "Irritated",
      mealStart: 18,
      mealEnd: 20,
      mealReason: "the workshop shift is winding down",
      mealStatus: "Eating beside the workshop",
      mealMood: "Hungry",
    }),
    resident({
      id: "sal",
      name: "Sal Orin",
      role: "Courier",
      homeLocationId: "south-cottages",
      workLocationId: "square",
      energy: 84,
      hunger: 22,
      mood: "Restless",
      action: "deliver",
      workStart: 9,
      workEnd: 18,
      workReason: "the courier route is active",
      workStatus: "Checking the delivery board",
      workMood: "Alert",
      mealStart: 18,
      mealEnd: 20,
      mealLocationId: "square",
      mealReason: "the evening route is finished",
      mealStatus: "Eating near the square",
      eveningAction: "observe",
      eveningStart: 20,
      eveningEnd: 22,
      eveningLocationId: "square",
      eveningReason: "the evening crowd is worth watching",
      eveningStatus: "Watching the square",
      eveningMood: "Curious",
    }),
    resident({
      id: "irena",
      name: "Irena Vale",
      role: "Shopkeeper",
      homeLocationId: "east-cottages",
      workLocationId: "general-store",
      energy: 78,
      hunger: 31,
      mood: "Measured",
      workStart: 7,
      workEnd: 16,
      workReason: "the shelves need stocking before the doors open",
      workStatus: "Counting the shelves",
      mealStart: 12,
      mealEnd: 14,
      mealReason: "the lunch crowd has thinned",
      mealStatus: "Eating in the store room",
    }),
    resident({
      id: "thom",
      name: "Thom Reed",
      role: "Farmer",
      homeLocationId: "east-cottages",
      workLocationId: "farm",
      energy: 69,
      hunger: 18,
      mood: "Weathered",
      workStart: 6,
      workEnd: 15,
      workReason: "the west field needs tending",
      workStatus: "Checking the west field",
      workMood: "Patient",
      mealStart: 15,
      mealEnd: 17,
      mealLocationId: "farm",
      mealReason: "the afternoon work is done",
      mealStatus: "Eating by the tool shed",
    }),
    resident({
      id: "june",
      name: "June Lark",
      role: "Teacher",
      homeLocationId: "hill-houses",
      workLocationId: "schoolhouse",
      energy: 81,
      hunger: 25,
      mood: "Bright",
      workStart: 8,
      workEnd: 15,
      workReason: "the school bell is nearly due",
      workStatus: "Preparing the lesson board",
      workMood: "Attentive",
      mealStart: 15,
      mealEnd: 17,
      mealLocationId: "schoolhouse",
      mealReason: "the last lesson has ended",
      mealStatus: "Eating in the classroom",
    }),
    resident({
      id: "bram",
      name: "Bram Ash",
      role: "Carpenter",
      homeLocationId: "hill-houses",
      workLocationId: "workshop",
      energy: 62,
      hunger: 37,
      mood: "Restless",
      workStart: 9,
      workEnd: 18,
      workReason: "a frame is waiting at the workshop",
      workStatus: "Measuring a new frame",
      workMood: "Concentrated",
      mealStart: 18,
      mealEnd: 20,
      mealReason: "the saws have gone quiet",
      mealStatus: "Eating at the workshop bench",
    }),
    resident({
      id: "nell",
      name: "Nell Ward",
      role: "Healer",
      homeLocationId: "east-cottages",
      workLocationId: "clinic",
      energy: 76,
      hunger: 30,
      mood: "Steady",
      workStart: 8,
      workEnd: 17,
      workReason: "the clinic is opening for the morning",
      workStatus: "Preparing the clinic",
      workMood: "Steady",
      mealStart: 17,
      mealEnd: 19,
      mealLocationId: "clinic",
      mealReason: "the waiting room is empty",
      mealStatus: "Eating in the clinic kitchen",
    }),
    resident({
      id: "corin",
      name: "Corin Pike",
      role: "Innkeeper",
      homeLocationId: "hill-houses",
      workLocationId: "inn",
      energy: 70,
      hunger: 33,
      mood: "Wary",
      workStart: 14,
      workEnd: 22,
      workReason: "the inn will fill toward evening",
      workStatus: "Setting the tables",
      workMood: "Watchful",
      mealStart: 11,
      mealEnd: 13,
      mealLocationId: "inn",
      mealReason: "there is a quiet hour before guests arrive",
      mealStatus: "Eating in the inn kitchen",
    }),
    resident({
      id: "pella",
      name: "Pella Moss",
      role: "Gardener",
      homeLocationId: "south-cottages",
      workLocationId: "farm",
      energy: 83,
      hunger: 27,
      mood: "Restless",
      workStart: 6,
      workEnd: 14,
      workReason: "the garden beds need watering",
      workStatus: "Checking the garden beds",
      workMood: "Patient",
      mealStart: 14,
      mealEnd: 16,
      mealLocationId: "farm",
      mealReason: "the morning watering is finished",
      mealStatus: "Eating beside the greenhouse",
    }),
  ],
  relationships,
};

export const tinyTownSeed = {
  id: townSeed.id,
  name: townSeed.name,
  weather: townSeed.weather,
  locations: townSeed.locations.filter((location) => [
    "bakery",
    "square",
    "workshop",
    "south-cottages",
  ].includes(location.id)),
  residents: townSeed.residents.filter((resident) => ["mara", "otis", "sal"].includes(resident.id)),
  relationships: townSeed.relationships.filter((relationship) => [
    "mara",
    "otis",
    "sal",
  ].includes(relationship.fromId) && [
    "mara",
    "otis",
    "sal",
  ].includes(relationship.toId)),
};
