export const demoTown = {
  id: "rookwood",
  name: "Rookwood",
  mode: "demo",
  day: 1,
  clock: "08:42 UTC",
  weather: "Cold and clear",
  summary: "A three-resident seed while the real simulation is being built.",
  locations: [
    { id: "bakery", name: "Sunrise Bakery", type: "Workplace", x: 24, y: 62 },
    { id: "square", name: "Founders Square", type: "Civic", x: 52, y: 42 },
    { id: "workshop", name: "North Workshop", type: "Workplace", x: 76, y: 25 },
    { id: "cottages", name: "South Cottages", type: "Residential", x: 66, y: 76 },
  ],
  residents: [
    {
      id: "mara",
      name: "Mara Venn",
      role: "Baker",
      location: "Sunrise Bakery",
      status: "Opening the ovens",
      mood: "Focused",
      energy: 72,
      x: 24,
      y: 62,
    },
    {
      id: "otis",
      name: "Otis Bell",
      role: "Mechanic",
      location: "North Workshop",
      status: "Sorting a stubborn gearbox",
      mood: "Irritated",
      energy: 58,
      x: 76,
      y: 25,
    },
    {
      id: "sal",
      name: "Sal Orin",
      role: "Courier",
      location: "Founders Square",
      status: "Waiting for a delivery",
      mood: "Restless",
      energy: 84,
      x: 52,
      y: 42,
    },
  ],
};

export const demoEvents = [
  {
    id: "event-003",
    time: "08:42",
    actor: "Sal Orin",
    type: "observation",
    text: "noticed that the north road is unusually quiet",
  },
  {
    id: "event-002",
    time: "08:31",
    actor: "Otis Bell",
    type: "routine",
    text: "started work at North Workshop",
  },
  {
    id: "event-001",
    time: "08:12",
    actor: "Mara Venn",
    type: "routine",
    text: "opened Sunrise Bakery",
  },
];
